"""Canonical four-level category taxonomy.

Canonical keys are English PascalCase and are the stable API/database/prompt
identifiers. User-facing text lives in display labels. Prompts may emit only:

- L2 Business Type keys for transaction/store categories.
- L4 Category keys for line-item categories.

L1 Industry and L3 Family are deterministic parent/group levels for reporting.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Iterable, Mapping


@dataclass(frozen=True)
class CategoryDefinition:
    key: str
    level: int
    parent_key: str | None
    display_labels: Mapping[str, str]
    is_sensitive: bool
    sort_order: int


def _category(
    key: str,
    level: int,
    parent_key: str | None,
    *,
    en: str,
    es: str,
    pt: str,
    is_sensitive: bool = False,
    sort_order: int,
) -> CategoryDefinition:
    return CategoryDefinition(
        key=key,
        level=level,
        parent_key=parent_key,
        display_labels={"en": en, "es": es, "pt": pt},
        is_sensitive=is_sensitive,
        sort_order=sort_order,
    )


V4_STORE_CATEGORY_TAXONOMY: tuple[CategoryDefinition, ...] = (
    _category(
        "SupermarketsIndustry",
        1,
        None,
        en="Supermarkets",
        es="Supermercados",
        pt="Supermercados",
        sort_order=1,
    ),
    _category(
        "Supermarket",
        2,
        "SupermarketsIndustry",
        en="Supermarket",
        es="Supermercado",
        pt="Supermercado",
        sort_order=1,
    ),
    _category(
        "Wholesale",
        2,
        "SupermarketsIndustry",
        en="Wholesale",
        es="Mayorista",
        pt="Atacado",
        sort_order=2,
    ),
    _category(
        "RestaurantsIndustry",
        1,
        None,
        en="Restaurants",
        es="Restaurantes",
        pt="Restaurantes",
        sort_order=2,
    ),
    _category(
        "Restaurant",
        2,
        "RestaurantsIndustry",
        en="Restaurant",
        es="Restaurante",
        pt="Restaurante",
        sort_order=1,
    ),
    _category(
        "NeighborhoodCommerceIndustry",
        1,
        None,
        en="Neighborhood Commerce",
        es="Comercio de Barrio",
        pt="Comercio de Bairro",
        sort_order=3,
    ),
    _category(
        "Almacen",
        2,
        "NeighborhoodCommerceIndustry",
        en="Corner Store",
        es="Almacén",
        pt="Armazém",
        sort_order=1,
    ),
    _category(
        "Minimarket",
        2,
        "NeighborhoodCommerceIndustry",
        en="Minimarket",
        es="Minimarket",
        pt="Minimercado",
        sort_order=2,
    ),
    _category(
        "OpenMarket",
        2,
        "NeighborhoodCommerceIndustry",
        en="Open Market",
        es="Feria",
        pt="Feira",
        sort_order=3,
    ),
    _category(
        "Kiosk",
        2,
        "NeighborhoodCommerceIndustry",
        en="Kiosk",
        es="Kiosco",
        pt="Quiosque",
        sort_order=4,
    ),
    _category(
        "LiquorStore",
        2,
        "NeighborhoodCommerceIndustry",
        en="Liquor Store",
        es="Botillería",
        pt="Loja de Bebidas",
        sort_order=5,
    ),
    _category(
        "Bakery",
        2,
        "NeighborhoodCommerceIndustry",
        en="Bakery",
        es="Panadería",
        pt="Padaria",
        sort_order=6,
    ),
    _category(
        "Butcher",
        2,
        "NeighborhoodCommerceIndustry",
        en="Butcher",
        es="Carnicería",
        pt="Açougue",
        sort_order=7,
    ),
    _category("HousingIndustry", 1, None, en="Housing", es="Vivienda", pt="Moradia", sort_order=4),
    _category(
        "UtilityCompany",
        2,
        "HousingIndustry",
        en="Utility Company",
        es="Compañía de Servicios",
        pt="Concessionária",
        sort_order=1,
    ),
    _category(
        "PropertyAdmin",
        2,
        "HousingIndustry",
        en="Property Administration",
        es="Administración de Propiedad",
        pt="Administração Predial",
        sort_order=2,
    ),
    _category(
        "HealthWellnessIndustry",
        1,
        None,
        en="Health and Wellness",
        es="Salud y Bienestar",
        pt="Saúde e Bem-estar",
        is_sensitive=True,
        sort_order=5,
    ),
    _category(
        "Pharmacy",
        2,
        "HealthWellnessIndustry",
        en="Pharmacy",
        es="Farmacia",
        pt="Farmácia",
        is_sensitive=True,
        sort_order=1,
    ),
    _category(
        "Medical",
        2,
        "HealthWellnessIndustry",
        en="Medical",
        es="Médico",
        pt="Médico",
        is_sensitive=True,
        sort_order=2,
    ),
    _category(
        "Veterinary",
        2,
        "HealthWellnessIndustry",
        en="Veterinary",
        es="Veterinaria",
        pt="Veterinária",
        sort_order=3,
    ),
    _category(
        "HealthBeauty",
        2,
        "HealthWellnessIndustry",
        en="Health and Beauty",
        es="Salud y Belleza",
        pt="Saúde e Beleza",
        sort_order=4,
    ),
    _category(
        "GeneralStoresIndustry",
        1,
        None,
        en="General Stores",
        es="Tiendas Generales",
        pt="Lojas Gerais",
        sort_order=6,
    ),
    _category(
        "Bazaar", 2, "GeneralStoresIndustry", en="Bazaar", es="Bazar", pt="Bazar", sort_order=1
    ),
    _category(
        "ClothingStore",
        2,
        "GeneralStoresIndustry",
        en="Clothing Store",
        es="Tienda de Ropa",
        pt="Loja de Roupas",
        sort_order=2,
    ),
    _category(
        "ElectronicsStore",
        2,
        "GeneralStoresIndustry",
        en="Electronics Store",
        es="Tienda de Electrónica",
        pt="Loja de Eletrônicos",
        sort_order=3,
    ),
    _category(
        "HomeGoods",
        2,
        "GeneralStoresIndustry",
        en="Home Goods",
        es="Artículos de Hogar",
        pt="Artigos para Casa",
        sort_order=4,
    ),
    _category(
        "FurnitureStore",
        2,
        "GeneralStoresIndustry",
        en="Furniture Store",
        es="Mueblería",
        pt="Loja de Móveis",
        sort_order=5,
    ),
    _category(
        "Hardware",
        2,
        "GeneralStoresIndustry",
        en="Hardware Store",
        es="Ferretería",
        pt="Ferragem",
        sort_order=6,
    ),
    _category(
        "GardenCenter",
        2,
        "GeneralStoresIndustry",
        en="Garden Center",
        es="Vivero/Jardinería",
        pt="Jardinagem",
        sort_order=7,
    ),
    _category(
        "SpecialtyStoresIndustry",
        1,
        None,
        en="Specialty Stores",
        es="Tiendas Especializadas",
        pt="Lojas Especializadas",
        sort_order=7,
    ),
    _category(
        "PetShop",
        2,
        "SpecialtyStoresIndustry",
        en="Pet Shop",
        es="Tienda de Mascotas",
        pt="Pet Shop",
        sort_order=1,
    ),
    _category(
        "BookStore",
        2,
        "SpecialtyStoresIndustry",
        en="Book Store",
        es="Librería",
        pt="Livraria",
        sort_order=2,
    ),
    _category(
        "OfficeSupplies",
        2,
        "SpecialtyStoresIndustry",
        en="Office Supplies",
        es="Artículos de Oficina",
        pt="Papelaria",
        sort_order=3,
    ),
    _category(
        "SportsStore",
        2,
        "SpecialtyStoresIndustry",
        en="Sports Store",
        es="Tienda Deportiva",
        pt="Loja Esportiva",
        sort_order=4,
    ),
    _category(
        "ToyStore",
        2,
        "SpecialtyStoresIndustry",
        en="Toy Store",
        es="Juguetería",
        pt="Loja de Brinquedos",
        sort_order=5,
    ),
    _category(
        "AccessoriesOptical",
        2,
        "SpecialtyStoresIndustry",
        en="Accessories and Optical",
        es="Accesorios y Óptica",
        pt="Acessórios e Ótica",
        sort_order=6,
    ),
    _category(
        "OnlineStore",
        2,
        "SpecialtyStoresIndustry",
        en="Online Store",
        es="Tienda Online",
        pt="Loja Online",
        sort_order=7,
    ),
    _category(
        "TransportVehicleIndustry",
        1,
        None,
        en="Transport and Vehicle",
        es="Transporte y Vehículo",
        pt="Transporte e Veículo",
        sort_order=8,
    ),
    _category(
        "AutoShop",
        2,
        "TransportVehicleIndustry",
        en="Auto Shop",
        es="Tienda Automotriz",
        pt="Autopeças",
        sort_order=1,
    ),
    _category(
        "GasStation",
        2,
        "TransportVehicleIndustry",
        en="Gas Station",
        es="Estación de Servicio",
        pt="Posto de Combustível",
        sort_order=2,
    ),
    _category(
        "Transport",
        2,
        "TransportVehicleIndustry",
        en="Transport",
        es="Transporte",
        pt="Transporte",
        sort_order=3,
    ),
    _category(
        "EducationIndustry", 1, None, en="Education", es="Educación", pt="Educação", sort_order=9
    ),
    _category(
        "Education",
        2,
        "EducationIndustry",
        en="Education",
        es="Educación",
        pt="Educação",
        sort_order=1,
    ),
    _category(
        "ServicesFinanceIndustry",
        1,
        None,
        en="Services and Finance",
        es="Servicios y Finanzas",
        pt="Serviços e Finanças",
        is_sensitive=True,
        sort_order=10,
    ),
    _category(
        "GeneralServices",
        2,
        "ServicesFinanceIndustry",
        en="General Services",
        es="Servicios Generales",
        pt="Serviços Gerais",
        sort_order=1,
    ),
    _category(
        "BankingFinance",
        2,
        "ServicesFinanceIndustry",
        en="Banking and Finance",
        es="Banca y Finanzas",
        pt="Banco e Finanças",
        is_sensitive=True,
        sort_order=2,
    ),
    _category(
        "TravelAgency",
        2,
        "ServicesFinanceIndustry",
        en="Travel Agency",
        es="Agencia de Viajes",
        pt="Agência de Viagens",
        sort_order=3,
    ),
    _category(
        "SubscriptionService",
        2,
        "ServicesFinanceIndustry",
        en="Subscription Service",
        es="Servicio de Suscripción",
        pt="Serviço de Assinatura",
        sort_order=4,
    ),
    _category(
        "Government",
        2,
        "ServicesFinanceIndustry",
        en="Government",
        es="Gobierno",
        pt="Governo",
        sort_order=5,
    ),
    _category(
        "EntertainmentLodgingIndustry",
        1,
        None,
        en="Entertainment and Lodging",
        es="Entretenimiento y Hospedaje",
        pt="Entretenimento e Hospedagem",
        sort_order=11,
    ),
    _category(
        "Lodging",
        2,
        "EntertainmentLodgingIndustry",
        en="Lodging",
        es="Hospedaje",
        pt="Hospedagem",
        sort_order=1,
    ),
    _category(
        "Entertainment",
        2,
        "EntertainmentLodgingIndustry",
        en="Entertainment",
        es="Entretenimiento",
        pt="Entretenimento",
        sort_order=2,
    ),
    _category(
        "Casino",
        2,
        "EntertainmentLodgingIndustry",
        en="Casino",
        es="Casino",
        pt="Cassino",
        is_sensitive=True,
        sort_order=3,
    ),
    _category("OtherIndustry", 1, None, en="Other", es="Otros", pt="Outros", sort_order=12),
    _category(
        "CharityDonation",
        2,
        "OtherIndustry",
        en="Charity or Donation",
        es="Caridad o Donación",
        pt="Caridade ou Doação",
        is_sensitive=True,
        sort_order=1,
    ),
    _category("Other", 2, "OtherIndustry", en="Other", es="Otro", pt="Outro", sort_order=2),
)

V4_ITEM_CATEGORY_TAXONOMY: tuple[CategoryDefinition, ...] = (
    _category(
        "FreshFood",
        3,
        None,
        en="Fresh Food",
        es="Alimentos Frescos",
        pt="Alimentos Frescos",
        sort_order=1,
    ),
    _category(
        "Produce",
        4,
        "FreshFood",
        en="Produce",
        es="Frutas y Verduras",
        pt="Hortifruti",
        sort_order=1,
    ),
    _category(
        "MeatSeafood",
        4,
        "FreshFood",
        en="Meat and Seafood",
        es="Carnes y Pescados",
        pt="Carnes e Pescados",
        sort_order=2,
    ),
    _category(
        "BreadPastry",
        4,
        "FreshFood",
        en="Bread and Pastry",
        es="Panadería y Pastelería",
        pt="Pães e Confeitaria",
        sort_order=3,
    ),
    _category(
        "DairyEggs",
        4,
        "FreshFood",
        en="Dairy and Eggs",
        es="Lácteos y Huevos",
        pt="Laticínios e Ovos",
        sort_order=4,
    ),
    _category(
        "PackagedFood",
        3,
        None,
        en="Packaged Food",
        es="Alimentos Envasados",
        pt="Alimentos Embalados",
        sort_order=2,
    ),
    _category("Pantry", 4, "PackagedFood", en="Pantry", es="Despensa", pt="Despensa", sort_order=1),
    _category(
        "FrozenFoods",
        4,
        "PackagedFood",
        en="Frozen Foods",
        es="Congelados",
        pt="Congelados",
        sort_order=2,
    ),
    _category("Snacks", 4, "PackagedFood", en="Snacks", es="Snacks", pt="Lanches", sort_order=3),
    _category(
        "Beverages", 4, "PackagedFood", en="Beverages", es="Bebidas", pt="Bebidas", sort_order=4
    ),
    _category(
        "PreparedMeals",
        3,
        None,
        en="Prepared Food",
        es="Comida Preparada",
        pt="Comida Preparada",
        sort_order=3,
    ),
    _category(
        "PreparedFood",
        4,
        "PreparedMeals",
        en="Prepared Food",
        es="Comida Preparada",
        pt="Comida Preparada",
        sort_order=1,
    ),
    _category(
        "HealthPersonalCareFamily",
        3,
        None,
        en="Health and Personal Care",
        es="Salud y Cuidado Personal",
        pt="Saúde e Cuidado Pessoal",
        is_sensitive=True,
        sort_order=4,
    ),
    _category(
        "BeautyCosmetics",
        4,
        "HealthPersonalCareFamily",
        en="Beauty and Cosmetics",
        es="Belleza y Cosméticos",
        pt="Beleza e Cosméticos",
        sort_order=1,
    ),
    _category(
        "PersonalCare",
        4,
        "HealthPersonalCareFamily",
        en="Personal Care",
        es="Cuidado Personal",
        pt="Cuidado Pessoal",
        sort_order=2,
    ),
    _category(
        "Medications",
        4,
        "HealthPersonalCareFamily",
        en="Medications",
        es="Medicamentos",
        pt="Medicamentos",
        is_sensitive=True,
        sort_order=3,
    ),
    _category(
        "Supplements",
        4,
        "HealthPersonalCareFamily",
        en="Supplements",
        es="Suplementos",
        pt="Suplementos",
        is_sensitive=True,
        sort_order=4,
    ),
    _category(
        "BabyProducts",
        4,
        "HealthPersonalCareFamily",
        en="Baby Products",
        es="Productos de Bebé",
        pt="Produtos de Bebê",
        sort_order=5,
    ),
    _category("HouseholdFamily", 3, None, en="Household", es="Hogar", pt="Casa", sort_order=5),
    _category(
        "CleaningSupplies",
        4,
        "HouseholdFamily",
        en="Cleaning Supplies",
        es="Artículos de Limpieza",
        pt="Produtos de Limpeza",
        sort_order=1,
    ),
    _category(
        "HomeEssentials",
        4,
        "HouseholdFamily",
        en="Home Essentials",
        es="Esenciales del Hogar",
        pt="Essenciais da Casa",
        sort_order=2,
    ),
    _category(
        "PetSupplies",
        4,
        "HouseholdFamily",
        en="Pet Supplies",
        es="Artículos para Mascotas",
        pt="Suprimentos para Animais",
        sort_order=3,
    ),
    _category(
        "PetFood",
        4,
        "HouseholdFamily",
        en="Pet Food",
        es="Alimento para Mascotas",
        pt="Ração",
        sort_order=4,
    ),
    _category(
        "Furnishings",
        4,
        "HouseholdFamily",
        en="Furnishings",
        es="Muebles y Decoración",
        pt="Móveis e Decoração",
        sort_order=5,
    ),
    _category(
        "GeneralProductsFamily",
        3,
        None,
        en="General Products",
        es="Productos Generales",
        pt="Produtos Gerais",
        sort_order=6,
    ),
    _category(
        "Apparel", 4, "GeneralProductsFamily", en="Apparel", es="Ropa", pt="Roupas", sort_order=1
    ),
    _category(
        "Technology",
        4,
        "GeneralProductsFamily",
        en="Technology",
        es="Tecnología",
        pt="Tecnologia",
        sort_order=2,
    ),
    _category(
        "Tools",
        4,
        "GeneralProductsFamily",
        en="Tools",
        es="Herramientas",
        pt="Ferramentas",
        sort_order=3,
    ),
    _category(
        "Garden", 4, "GeneralProductsFamily", en="Garden", es="Jardín", pt="Jardim", sort_order=4
    ),
    _category(
        "CarAccessories",
        4,
        "GeneralProductsFamily",
        en="Car Accessories",
        es="Accesorios de Auto",
        pt="Acessórios de Carro",
        sort_order=5,
    ),
    _category(
        "SportsOutdoors",
        4,
        "GeneralProductsFamily",
        en="Sports and Outdoors",
        es="Deportes y Aire Libre",
        pt="Esportes e Ar Livre",
        sort_order=6,
    ),
    _category(
        "ToysGames",
        4,
        "GeneralProductsFamily",
        en="Toys and Games",
        es="Juguetes y Juegos",
        pt="Brinquedos e Jogos",
        sort_order=7,
    ),
    _category(
        "BooksMedia",
        4,
        "GeneralProductsFamily",
        en="Books and Media",
        es="Libros y Medios",
        pt="Livros e Mídia",
        sort_order=8,
    ),
    _category(
        "OfficeStationery",
        4,
        "GeneralProductsFamily",
        en="Office and Stationery",
        es="Oficina y Papelería",
        pt="Escritório e Papelaria",
        sort_order=9,
    ),
    _category(
        "Crafts",
        4,
        "GeneralProductsFamily",
        en="Crafts",
        es="Manualidades",
        pt="Artesanato",
        sort_order=10,
    ),
    _category(
        "ServicesFeesFamily",
        3,
        None,
        en="Services and Fees",
        es="Servicios y Cargos",
        pt="Serviços e Taxas",
        sort_order=7,
    ),
    _category(
        "ServiceCharge",
        4,
        "ServicesFeesFamily",
        en="Service Charge",
        es="Cargo por Servicio",
        pt="Taxa de Serviço",
        sort_order=1,
    ),
    _category(
        "TaxFees",
        4,
        "ServicesFeesFamily",
        en="Taxes and Fees",
        es="Impuestos y Tasas",
        pt="Impostos e Taxas",
        sort_order=2,
    ),
    _category(
        "Subscription",
        4,
        "ServicesFeesFamily",
        en="Subscription",
        es="Suscripción",
        pt="Assinatura",
        sort_order=3,
    ),
    _category(
        "Insurance",
        4,
        "ServicesFeesFamily",
        en="Insurance",
        es="Seguro",
        pt="Seguro",
        is_sensitive=True,
        sort_order=4,
    ),
    _category(
        "LoanPayment",
        4,
        "ServicesFeesFamily",
        en="Loan Payment",
        es="Pago de Préstamo",
        pt="Pagamento de Empréstimo",
        is_sensitive=True,
        sort_order=5,
    ),
    _category(
        "TicketsEvents",
        4,
        "ServicesFeesFamily",
        en="Tickets and Events",
        es="Entradas y Eventos",
        pt="Ingressos e Eventos",
        sort_order=6,
    ),
    _category(
        "HouseholdBills",
        4,
        "ServicesFeesFamily",
        en="Household Bills",
        es="Cuentas del Hogar",
        pt="Contas da Casa",
        sort_order=7,
    ),
    _category(
        "CondoFees",
        4,
        "ServicesFeesFamily",
        en="Condo Fees",
        es="Gastos Comunes",
        pt="Condomínio",
        sort_order=8,
    ),
    _category(
        "EducationFees",
        4,
        "ServicesFeesFamily",
        en="Education Fees",
        es="Gastos Educacionales",
        pt="Taxas Educacionais",
        sort_order=9,
    ),
    _category(
        "VicesFamily",
        3,
        None,
        en="Vices",
        es="Vicios",
        pt="Vícios",
        is_sensitive=True,
        sort_order=8,
    ),
    _category(
        "Alcohol",
        4,
        "VicesFamily",
        en="Alcohol",
        es="Alcohol",
        pt="Álcool",
        is_sensitive=True,
        sort_order=1,
    ),
    _category(
        "Tobacco",
        4,
        "VicesFamily",
        en="Tobacco",
        es="Tabaco",
        pt="Tabaco",
        is_sensitive=True,
        sort_order=2,
    ),
    _category(
        "GamesOfChance",
        4,
        "VicesFamily",
        en="Games of Chance",
        es="Juegos de Azar",
        pt="Jogos de Azar",
        is_sensitive=True,
        sort_order=3,
    ),
    _category("OtherFamily", 3, None, en="Other", es="Otros", pt="Outros", sort_order=9),
    _category(
        "OtherItem",
        4,
        "OtherFamily",
        en="Other Item",
        es="Otro Ítem",
        pt="Outro Item",
        sort_order=1,
    ),
)


def _keys_at_level(
    taxonomy: Iterable[CategoryDefinition],
    level: int,
) -> tuple[str, ...]:
    return tuple(category.key for category in taxonomy if category.level == level)


V4_INDUSTRY_KEYS: tuple[str, ...] = _keys_at_level(V4_STORE_CATEGORY_TAXONOMY, 1)
V4_STORE_CATEGORY_KEYS: tuple[str, ...] = _keys_at_level(V4_STORE_CATEGORY_TAXONOMY, 2)
V4_ITEM_FAMILY_KEYS: tuple[str, ...] = _keys_at_level(V4_ITEM_CATEGORY_TAXONOMY, 3)
V4_CATEGORY_KEYS: tuple[str, ...] = _keys_at_level(V4_ITEM_CATEGORY_TAXONOMY, 4)

SPANISH_TO_ENGLISH_CATEGORY_KEYS: dict[str, str] = {
    "Supermercado": "Pantry",
    "Panaderia": "BreadPastry",
    "Miscelaneo": "OtherItem",
    "Alimentacion": "Pantry",
    "Transporte": "ServiceCharge",
    "Hogar": "HomeEssentials",
    "Salud": "Medications",
    "Educacion": "EducationFees",
    "Entretenimiento": "TicketsEvents",
    "Vestimenta": "Apparel",
    "Servicios": "ServiceCharge",
    "Finanzas": "LoanPayment",
    "Tecnologia": "Technology",
    "Mascotas": "PetSupplies",
    "Otro": "OtherItem",
}


def render_v4_taxonomy_prompt() -> str:
    return render_v4_item_taxonomy_prompt()


def render_v4_item_taxonomy_prompt() -> str:
    return _render_prompt_taxonomy(
        title="ITEM CATEGORY TAXONOMY (V4 — choose only L4 English PascalCase keys)",
        taxonomy=V4_ITEM_CATEGORY_TAXONOMY,
        parent_level=3,
        child_level=4,
        parent_label="L3 Family",
        child_label="L4 Categories",
    )


def render_v4_store_taxonomy_prompt() -> str:
    return _render_prompt_taxonomy(
        title="STORE CATEGORY TAXONOMY (V4 — choose only L2 English PascalCase keys)",
        taxonomy=V4_STORE_CATEGORY_TAXONOMY,
        parent_level=1,
        child_level=2,
        parent_label="L1 Industry",
        child_label="L2 Business Types",
    )


def _render_prompt_taxonomy(
    *,
    title: str,
    taxonomy: Iterable[CategoryDefinition],
    parent_level: int,
    child_level: int,
    parent_label: str,
    child_label: str,
) -> str:
    categories = tuple(taxonomy)
    children_by_parent: dict[str | None, list[CategoryDefinition]] = {}
    for category in categories:
        children_by_parent.setdefault(category.parent_key, []).append(category)

    lines = [title, ""]
    for parent in [category for category in categories if category.level == parent_level]:
        lines.append(f"{parent_label} {parent.key} (es: {parent.display_labels['es']}):")
        children = [
            child for child in children_by_parent.get(parent.key, []) if child.level == child_level
        ]
        if children:
            lines.append(
                f"  {child_label}: " + ", ".join(_prompt_label(child) for child in children)
            )
    return "\n".join(lines)


def _prompt_label(category: CategoryDefinition) -> str:
    es_label = category.display_labels["es"]
    return f"{category.key} (es: {es_label})"
