/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_api_v1_transactions_get"];
        put?: never;
        /** Create Transaction */
        post: operations["create_transaction_api_v1_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transaction */
        get: operations["get_transaction_api_v1_transactions__transaction_id__get"];
        put?: never;
        post?: never;
        /** Delete Transaction */
        delete: operations["delete_transaction_api_v1_transactions__transaction_id__delete"];
        options?: never;
        head?: never;
        /** Update Transaction */
        patch: operations["update_transaction_api_v1_transactions__transaction_id__patch"];
        trace?: never;
    };
    "/api/v1/transactions/batch-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch Update Transactions */
        post: operations["batch_update_transactions_api_v1_transactions_batch_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/batch-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch Delete Transactions */
        post: operations["batch_delete_transactions_api_v1_transactions_batch_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Consents */
        get: operations["get_consents_api_v1_consent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/consent/{purpose}/grant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grant */
        post: operations["grant_api_v1_consent__purpose__grant_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/consent/{purpose}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke */
        post: operations["revoke_api_v1_consent__purpose__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/consent/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit Trail */
        get: operations["get_audit_trail_api_v1_consent_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/consent/processing-register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Processing Register */
        get: operations["get_processing_register_api_v1_consent_processing_register_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/privacy/data-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Data Access
         * @description GDPR Art 15 / Law 21.719 Art 8 / PIPEDA / CCPA — right of access.
         */
        get: operations["data_access_api_v1_privacy_data_access_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/privacy/rectification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rectification
         * @description GDPR Art 16 / Law 21.719 / CPRA — right to rectification.
         */
        post: operations["rectification_api_v1_privacy_rectification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/privacy/erasure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Erasure
         * @description GDPR Art 17 / Law 21.719 / CCPA — right to erasure.
         *
         *     Soft-delete: anonymizes PII in user profile, transactions, items, images;
         *     revokes all consents. Does not hard-delete rows (audit trail per D4).
         */
        post: operations["erasure_api_v1_privacy_erasure_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/privacy/portability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Portability
         * @description GDPR Art 20 / Law 21.719 / CCPA — right to data portability.
         *
         *     Returns all user data in machine-readable JSON format.
         */
        get: operations["portability_api_v1_privacy_portability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Scan */
        post: operations["submit_scan_api_v1_scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Process Scan
         * @description Manually trigger extraction for a scan (retry or reprocess).
         */
        post: operations["trigger_process_scan_api_v1_scans__scan_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan Events Sse */
        get: operations["scan_events_sse_api_v1_scans__scan_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_api_v1_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEventResponse */
        AuditEventResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Event Type */
            event_type: string;
            /** Resource Type */
            resource_type?: string | null;
            /** Resource Id */
            resource_id?: string | null;
            /** Details */
            details?: string | null;
            /** Ip Address */
            ip_address?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AuditListResponse */
        AuditListResponse: {
            /** Events */
            events: components["schemas"]["AuditEventResponse"][];
        };
        /** BatchDeleteRequest */
        BatchDeleteRequest: {
            /** Transaction Ids */
            transaction_ids: string[];
        };
        /** BatchResult */
        BatchResult: {
            /** Count */
            count: number;
        };
        /** BatchUpdateFields */
        BatchUpdateFields: {
            /** Merchant */
            merchant?: string | null;
            /** Store Category Id */
            store_category_id?: string | null;
        };
        /** BatchUpdateRequest */
        BatchUpdateRequest: {
            /** Transaction Ids */
            transaction_ids: string[];
            updates: components["schemas"]["BatchUpdateFields"];
        };
        /** Body_submit_scan_api_v1_scans_post */
        Body_submit_scan_api_v1_scans_post: {
            /** File */
            file: string;
        };
        /** ConsentGrant */
        ConsentGrant: {
            /**
             * Jurisdiction
             * @description Jurisdiction code: CL, EU, CA, US-CA
             * @enum {string}
             */
            jurisdiction: "CL" | "EU" | "CA" | "US-CA";
            /**
             * Consent Version
             * @default 1.0
             */
            consent_version: string;
        };
        /** ConsentListResponse */
        ConsentListResponse: {
            /** Consents */
            consents: components["schemas"]["ConsentResponse"][];
        };
        /** ConsentResponse */
        ConsentResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Purpose */
            purpose: string;
            /** Status */
            status: string;
            /** Legal Basis */
            legal_basis: string;
            /** Jurisdiction */
            jurisdiction: string;
            /**
             * Granted At
             * Format: date-time
             */
            granted_at: string;
            /** Revoked At */
            revoked_at?: string | null;
            /** Consent Version */
            consent_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DataAccessResponse */
        DataAccessResponse: {
            user: components["schemas"]["UserDataExport"];
            /** Consents */
            consents: components["schemas"]["ConsentResponse"][];
            /** Transactions Count */
            transactions_count: number;
            /**
             * Exported At
             * Format: date-time
             */
            exported_at: string;
        };
        /** ErasureResponse */
        ErasureResponse: {
            /** Consents Revoked */
            consents_revoked: number;
            /** Transactions Anonymized */
            transactions_anonymized: number;
            /** User Anonymized */
            user_anonymized: boolean;
            /**
             * Audit Event Id
             * Format: uuid
             */
            audit_event_id: string;
            /**
             * Erased At
             * Format: date-time
             */
            erased_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PaginatedResponse[TransactionListItem] */
        PaginatedResponse_TransactionListItem_: {
            /** Data */
            data: components["schemas"]["TransactionListItem"][];
            /** Cursor */
            cursor?: string | null;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
        };
        /** PortabilityResponse */
        PortabilityResponse: {
            /**
             * Format
             * @default application/json
             */
            format: string;
            /**
             * Version
             * @default 1.0
             */
            version: string;
            /**
             * Exported At
             * Format: date-time
             */
            exported_at: string;
            user: components["schemas"]["UserDataExport"];
            /** Consents */
            consents: components["schemas"]["ConsentResponse"][];
            /** Transactions */
            transactions: components["schemas"]["PortabilityTransaction"][];
            /** Total Transactions */
            total_transactions: number;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /** PortabilityTransaction */
        PortabilityTransaction: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Transaction Date
             * Format: date
             */
            transaction_date: string;
            /** Merchant */
            merchant: string;
            /** Total Minor */
            total_minor: number;
            /** Currency */
            currency: string;
            /** Amount Usd Minor */
            amount_usd_minor?: number | null;
            /** Receipt Type */
            receipt_type?: string | null;
            /** Country */
            country?: string | null;
            /** City */
            city?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProcessingRegisterResponse */
        ProcessingRegisterResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Purpose */
            purpose: string;
            /** Description */
            description: string;
            /** Legal Basis */
            legal_basis: string;
            /** Data Categories */
            data_categories: string;
            /** Recipients */
            recipients: string;
            /** Retention Period */
            retention_period: string;
            /** Jurisdictions */
            jurisdictions: string;
            /** Is Active */
            is_active: boolean;
        };
        /** RectificationRequest */
        RectificationRequest: {
            /** Display Name */
            display_name?: string | null;
            /** Email */
            email?: string | null;
            /** Default Currency */
            default_currency?: string | null;
            /** Locale */
            locale?: string | null;
        };
        /** RectificationResponse */
        RectificationResponse: {
            /** Updated Fields */
            updated_fields: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ScanResult */
        ScanResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Processed At */
            processed_at?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
        };
        /** ScanSubmission */
        ScanSubmission: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Ownership Scope Id
             * Format: uuid
             */
            ownership_scope_id: string;
            /** Status */
            status: string;
            /** Original Filename */
            original_filename: string;
            /** Content Type */
            content_type: string;
            /** File Size Bytes */
            file_size_bytes: number;
            /** Image Path */
            image_path: string;
            /** Thumbnail Path */
            thumbnail_path?: string | null;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
        };
        /** TransactionCreate */
        TransactionCreate: {
            /**
             * Transaction Date
             * Format: date
             */
            transaction_date: string;
            /** Transaction Time */
            transaction_time?: string | null;
            /** Merchant */
            merchant: string;
            /** Store Category Id */
            store_category_id?: string | null;
            /** Total Minor */
            total_minor: number;
            /** Currency */
            currency: string;
            /** Receipt Type */
            receipt_type?: ("scan" | "manual" | "statement" | "import") | null;
            /** Country */
            country?: string | null;
            /** City */
            city?: string | null;
            /** Card Alias Id */
            card_alias_id?: string | null;
            /** Merchant Source */
            merchant_source?: ("ocr" | "user" | "ai" | "mapping") | null;
            /** Llm Tokens In */
            llm_tokens_in?: number | null;
            /** Llm Tokens Out */
            llm_tokens_out?: number | null;
            /** Llm Cost Usd */
            llm_cost_usd?: number | string | null;
            /** Scan Duration Ms */
            scan_duration_ms?: number | null;
            /** Llm Latency Ms */
            llm_latency_ms?: number | null;
            /** Queue Wait Ms */
            queue_wait_ms?: number | null;
            /** Thumbnail Gen Ms */
            thumbnail_gen_ms?: number | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["TransactionItemCreate"][];
            /**
             * Image Urls
             * @default []
             */
            image_urls: string[];
        };
        /** TransactionDetail */
        TransactionDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Transaction Date
             * Format: date
             */
            transaction_date: string;
            /** Transaction Time */
            transaction_time?: string | null;
            /** Merchant */
            merchant: string;
            /** Merchant User Edited At */
            merchant_user_edited_at?: string | null;
            /** Alias */
            alias?: string | null;
            /** Store Category Id */
            store_category_id?: string | null;
            /** Store Category User Edited At */
            store_category_user_edited_at?: string | null;
            /** Total Minor */
            total_minor: number;
            /** Currency */
            currency: string;
            /** Amount Usd Minor */
            amount_usd_minor?: number | null;
            /** Fx Rate To Usd */
            fx_rate_to_usd?: string | null;
            /** Fx Captured At */
            fx_captured_at?: string | null;
            /** Card Alias Id */
            card_alias_id?: string | null;
            /** Receipt Type */
            receipt_type?: string | null;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            /** Country */
            country?: string | null;
            /** City */
            city?: string | null;
            /** Llm Tokens In */
            llm_tokens_in?: number | null;
            /** Llm Tokens Out */
            llm_tokens_out?: number | null;
            /** Llm Cost Usd */
            llm_cost_usd?: string | null;
            /** Scan Duration Ms */
            scan_duration_ms?: number | null;
            /** Llm Latency Ms */
            llm_latency_ms?: number | null;
            /** Queue Wait Ms */
            queue_wait_ms?: number | null;
            /** Thumbnail Gen Ms */
            thumbnail_gen_ms?: number | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["TransactionItemResponse"][];
            /**
             * Images
             * @default []
             */
            images: components["schemas"]["TransactionImageResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TransactionImageResponse */
        TransactionImageResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Image Url */
            image_url: string;
            /** Is Thumbnail */
            is_thumbnail: boolean;
            /** Sort Order */
            sort_order: number;
        };
        /** TransactionItemCreate */
        TransactionItemCreate: {
            /** Name */
            name: string;
            /** Qty */
            qty?: number | null;
            /** Unit Price Minor */
            unit_price_minor?: number | null;
            /** Total Price Minor */
            total_price_minor: number;
            /** Item Category Id */
            item_category_id?: string | null;
            /** Subcategory */
            subcategory?: string | null;
            /** Category Source */
            category_source?: string | null;
            /**
             * Is Flagged
             * @default false
             */
            is_flagged: boolean;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** TransactionItemResponse */
        TransactionItemResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Name User Edited At */
            name_user_edited_at?: string | null;
            /** Qty */
            qty?: number | null;
            /** Unit Price Minor */
            unit_price_minor?: number | null;
            /** Total Price Minor */
            total_price_minor: number;
            /** Item Category Id */
            item_category_id?: string | null;
            /** Item Category User Edited At */
            item_category_user_edited_at?: string | null;
            /** Subcategory */
            subcategory?: string | null;
            /** Category Source */
            category_source?: string | null;
            /** Is Flagged */
            is_flagged: boolean;
            /** Sort Order */
            sort_order: number;
        };
        /** TransactionItemUpdate */
        TransactionItemUpdate: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name?: string | null;
            /** Qty */
            qty?: number | null;
            /** Unit Price Minor */
            unit_price_minor?: number | null;
            /** Total Price Minor */
            total_price_minor?: number | null;
            /** Item Category Id */
            item_category_id?: string | null;
            /** Subcategory */
            subcategory?: string | null;
            /** Category Source */
            category_source?: string | null;
            /** Is Flagged */
            is_flagged?: boolean | null;
        };
        /** TransactionListItem */
        TransactionListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Transaction Date
             * Format: date
             */
            transaction_date: string;
            /** Transaction Time */
            transaction_time?: string | null;
            /** Merchant */
            merchant: string;
            /** Merchant User Edited At */
            merchant_user_edited_at?: string | null;
            /** Alias */
            alias?: string | null;
            /** Store Category Id */
            store_category_id?: string | null;
            /** Store Category User Edited At */
            store_category_user_edited_at?: string | null;
            /** Total Minor */
            total_minor: number;
            /** Currency */
            currency: string;
            /** Amount Usd Minor */
            amount_usd_minor?: number | null;
            /** Fx Rate To Usd */
            fx_rate_to_usd?: string | null;
            /** Card Alias Id */
            card_alias_id?: string | null;
            /** Receipt Type */
            receipt_type?: string | null;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            /** Country */
            country?: string | null;
            /** City */
            city?: string | null;
            /**
             * Item Count
             * @default 0
             */
            item_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TransactionUpdate */
        TransactionUpdate: {
            /** Transaction Date */
            transaction_date?: string | null;
            /** Transaction Time */
            transaction_time?: string | null;
            /** Merchant */
            merchant?: string | null;
            /** Store Category Id */
            store_category_id?: string | null;
            /** Total Minor */
            total_minor?: number | null;
            /** Currency */
            currency?: string | null;
            /** Receipt Type */
            receipt_type?: string | null;
            /** Country */
            country?: string | null;
            /** City */
            city?: string | null;
            /** Card Alias Id */
            card_alias_id?: string | null;
            /** Items */
            items?: components["schemas"]["TransactionItemUpdate"][] | null;
        };
        /** UserDataExport */
        UserDataExport: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Default Currency */
            default_currency: string;
            /** Locale */
            locale: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_transactions_api_v1_transactions_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                date_from?: string | null;
                date_to?: string | null;
                category?: string | null;
                merchant?: string | null;
                currency?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_TransactionListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transaction_api_v1_transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transaction_api_v1_transactions__transaction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_transaction_api_v1_transactions__transaction_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_transaction_api_v1_transactions__transaction_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_update_transactions_api_v1_transactions_batch_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_delete_transactions_api_v1_transactions_batch_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_consents_api_v1_consent_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentListResponse"];
                };
            };
        };
    };
    grant_api_v1_consent__purpose__grant_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purpose: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentGrant"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_v1_consent__purpose__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purpose: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_trail_api_v1_consent_audit_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_processing_register_api_v1_consent_processing_register_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingRegisterResponse"][];
                };
            };
        };
    };
    data_access_api_v1_privacy_data_access_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataAccessResponse"];
                };
            };
        };
    };
    rectification_api_v1_privacy_rectification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RectificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RectificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    erasure_api_v1_privacy_erasure_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErasureResponse"];
                };
            };
        };
    };
    portability_api_v1_privacy_portability_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortabilityResponse"];
                };
            };
        };
    };
    submit_scan_api_v1_scans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_submit_scan_api_v1_scans_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanSubmission"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_process_scan_api_v1_scans__scan_id__process_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_events_sse_api_v1_scans__scan_id__events_get: {
        parameters: {
            query: {
                /** @description Firebase JWT for authentication */
                token: string;
            };
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_api_v1_metrics_get: {
        parameters: {
            query?: never;
            header?: {
                "x-metrics-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
