/**
 * gastify design tokens — Playful Geometric (single theme).
 *
 * DM-1 (2026-06-10): gastify adopts Gustify's Playful Geometric look as its
 * single visual identity — violet primary, amber/pink/emerald accents, cream
 * canvas, slate-900 ink — rendered with the geometric grammar (2–3px ink
 * borders, HARD zero-blur offset shadows, bold Outfit, framed surfaces).
 * Replaces the earlier warm 3-theme port of web/src/styles/global.css.
 *
 * Provenance of values: Gustify shared/design-tokens.ts (Playful Geometric).
 *
 * Vocabulary discipline: the `gt-*` Tailwind utility names + semantic role
 * keys are KEPT from the prior token layer so components don't churn — only
 * the VALUES changed. Generated by design-lab/scripts/generate-tokens-css.mjs
 * into design-lab/src/styles/tokens.css (single `:root` + `@theme inline`).
 *
 * Wiring into web/ later means porting THESE tokens into web (not matching
 * web's current warm CSS vars). mobile/ (RN) consumes this module via a
 * platform adapter. Values are px-unit-agnostic.
 */

export interface SemanticColors {
  bg: string;
  bgSecondary: string;
  bgTertiary: string;
  surface: string;
  primary: string;
  primaryHover: string;
  primaryLight: string;
  secondary: string;
  accent: string;
  success: string;
  warning: string;
  error: string;
  textPrimary: string;
  textSecondary: string;
  textTertiary: string;
  borderLight: string;
  borderMedium: string;
  chart1: string;
  chart2: string;
  chart3: string;
  chart4: string;
  chart5: string;
  chart6: string;
  positivePrimary: string;
  positiveBg: string;
  negativePrimary: string;
  negativeBg: string;
  neutralPrimary: string;
  neutralBg: string;
  /** ink color the HARD offset shadows are drawn in. */
  shadowColor: string;
  shadowColorLg: string;
}

export type SemanticColorKey = keyof SemanticColors;

/** Gustify Playful Geometric palette (named hexes). */
export const palette = {
  cream: "#FFFDF5",
  slate900: "#1E293B",
  slate500: "#64748B",
  slate400: "#94A3B8",
  slate200: "#E2E8F0",
  slate100: "#F1F5F9",
  white: "#FFFFFF",
  violet: "#8B5CF6",
  violetHover: "#7C3AED",
  violetSoft: "#EDE9FE",
  pink: "#F472B6",
  amber: "#FBBF24",
  emerald: "#34D399",
  emeraldInk: "#10B981",
  emeraldSoft: "#D1FAE5",
  blue: "#3B82F6",
  red: "#EF4444",
  redSoft: "#FEE2E2",
} as const;

/** The single theme — semantic roles mapped to the palette. */
export const colors: SemanticColors = {
  bg: palette.cream,
  bgSecondary: palette.white,
  bgTertiary: palette.slate100,
  surface: palette.white,
  primary: palette.violet,
  primaryHover: palette.violetHover,
  primaryLight: palette.violetSoft,
  secondary: palette.pink,
  accent: palette.amber,
  success: palette.emerald,
  warning: palette.amber,
  error: palette.red,
  textPrimary: palette.slate900,
  textSecondary: palette.slate500,
  textTertiary: palette.slate400,
  borderLight: palette.slate200, // soft divider (gt-line)
  borderMedium: palette.slate900, // INK identity border (gt-line-strong)
  chart1: palette.violet,
  chart2: palette.amber,
  chart3: palette.pink,
  chart4: palette.emerald,
  chart5: palette.blue,
  chart6: palette.slate500,
  positivePrimary: palette.emeraldInk,
  positiveBg: palette.emeraldSoft,
  negativePrimary: palette.red,
  negativeBg: palette.redSoft,
  neutralPrimary: palette.slate500,
  neutralBg: palette.slate100,
  shadowColor: palette.slate900,
  shadowColorLg: palette.slate900,
};

/** TS key → runtime CSS custom property (kept stable across the DM-1 swap). */
export const cssVarFor: Record<SemanticColorKey, string> = {
  bg: "--bg",
  bgSecondary: "--bg-secondary",
  bgTertiary: "--bg-tertiary",
  surface: "--surface",
  primary: "--primary",
  primaryHover: "--primary-hover",
  primaryLight: "--primary-light",
  secondary: "--secondary",
  accent: "--accent",
  success: "--success",
  warning: "--warning",
  error: "--error",
  textPrimary: "--text-primary",
  textSecondary: "--text-secondary",
  textTertiary: "--text-tertiary",
  borderLight: "--border-light",
  borderMedium: "--border-medium",
  chart1: "--chart-1",
  chart2: "--chart-2",
  chart3: "--chart-3",
  chart4: "--chart-4",
  chart5: "--chart-5",
  chart6: "--chart-6",
  positivePrimary: "--positive-primary",
  positiveBg: "--positive-bg",
  negativePrimary: "--negative-primary",
  negativeBg: "--negative-bg",
  neutralPrimary: "--neutral-primary",
  neutralBg: "--neutral-bg",
  shadowColor: "--shadow",
  shadowColorLg: "--shadow-lg",
} as const;

/**
 * TS key → Tailwind `gt-*` utility suffix (unchanged across DM-1).
 * `gt-line` = soft slate divider; `gt-line-strong` = the ink identity border.
 */
export const twKeyFor: Record<Exclude<SemanticColorKey, "shadowColor" | "shadowColorLg">, string> = {
  bg: "bg",
  bgSecondary: "bg-2",
  bgTertiary: "bg-3",
  surface: "surface",
  primary: "primary",
  primaryHover: "primary-hover",
  primaryLight: "primary-soft",
  secondary: "secondary",
  accent: "accent",
  success: "success",
  warning: "warning",
  error: "error",
  textPrimary: "ink",
  textSecondary: "ink-2",
  textTertiary: "ink-3",
  borderLight: "line",
  borderMedium: "line-strong",
  chart1: "chart-1",
  chart2: "chart-2",
  chart3: "chart-3",
  chart4: "chart-4",
  chart5: "chart-5",
  chart6: "chart-6",
  positivePrimary: "positive",
  positiveBg: "positive-bg",
  negativePrimary: "negative",
  negativeBg: "negative-bg",
  neutralPrimary: "neutral",
  neutralBg: "neutral-bg",
} as const;

/**
 * Typography (DM-16). Outfit everywhere — body AND display — at extrabold for
 * the geometric look, matching Gustify parity (Baloo 2 dropped). `display` is
 * kept as a separate alias (still Outfit) so `font-gt-display` keeps working and
 * the choice can be re-tuned in one place. Space Grotesk remains the alt face
 * for tabular/numeric contexts (charts).
 */
export const fontFamily = {
  body: "'Outfit', system-ui, -apple-system, sans-serif",
  display: "'Outfit', system-ui, -apple-system, sans-serif",
  alt: "'Space Grotesk', system-ui, sans-serif",
} as const;

export const fontWeight = {
  regular: 400,
  medium: 500,
  semibold: 600,
  bold: 700,
  extrabold: 800,
} as const;

/** px ramp (unchanged across DM-1). */
export const fontSize = {
  xs: 11,
  sm: 12,
  base: 13,
  md: 14,
  lg: 15,
  xl: 16,
  "2xl": 18,
  "3xl": 22,
  "4xl": 28,
  "5xl": 32,
  "6xl": 38,
  "7xl": 44,
} as const;

export const lineHeight = {
  tight: 1.1,
  snug: 1.2,
  normal: 1.5,
  relaxed: 1.6,
} as const;

/**
 * Radius (px) — SOFT scale (DM-16, Gustify parity). Bumped rounder so existing
 * class usage lands on the soft rungs: controls/tiles ~`lg`–`xl` (10–12),
 * cards/list wrappers `2xl` (16–20). `frame` is the emulated-device bezel
 * (AppSurface), a mockup-chrome constant, not a product-surface radius.
 *
 * Per-element convention: chips/badges/pills/avatars = `pill`; interactive
 * controls (Button/Input/IconButton/toggles) = `lg`–`xl`; framed icon tiles =
 * `lg`; containers/cards/list wrappers = `2xl`; hero/empty surfaces = `3xl`.
 */
export const radius = {
  sm: 6,
  md: 8,
  lg: 10,
  xl: 12,
  "2xl": 16,
  "3xl": 20,
  "4xl": 22,
  "5xl": 24,
  "6xl": 26,
  frame: 40,
  pill: 999,
} as const;

/**
 * Spacing scale (px) — the cohesion primitive (DM-16, ported from Gustify's
 * pg-N habit). Key == pixel value. Off-grid 6 and 10 are FIRST-CLASS (the
 * dominant row/chip rhythm). Emitted as `--spacing-gt-N` → enables gap-gt-10,
 * p-gt-16, px-gt-12, py-gt-10, space-y-gt-8, etc. Canonical pairings:
 *   card interior p-gt-16 · list-row p-gt-10 / gap-gt-10 · icon+label gap-gt-8
 *   chip/meta/trailing gap-gt-6 · meta-part gap-gt-4 · section header px-gt-12 py-gt-10
 */
export const spacing = {
  0: 0,
  2: 2,
  4: 4,
  6: 6,
  8: 8,
  10: 10,
  12: 12,
  14: 14,
  16: 16,
  20: 20,
  24: 24,
  28: 28,
  32: 32,
  40: 40,
  48: 48,
  64: 64,
} as const;

/**
 * HARD zero-blur offset shadows — the Playful Geometric signature. Drawn in
 * the ink color (var(--shadow)); blur MUST stay 0 or the identity breaks.
 */
export const shadow = {
  xs: "1px 1px 0px 0px var(--shadow)",
  sm: "2px 2px 0px 0px var(--shadow)",
  md: "4px 4px 0px 0px var(--shadow)",
  lg: "6px 6px 0px 0px var(--shadow)",
  xl: "8px 8px 0px 0px var(--shadow)",
  "2xl": "12px 12px 0px 0px var(--shadow)",
} as const;

export const motion = {
  duration: { fast: "120ms", base: "150ms", slow: "200ms", slower: "300ms" },
  easing: {
    out: "ease-out",
    inOut: "ease-in-out",
    bounce: "cubic-bezier(0.34, 1.56, 0.64, 1)",
  },
} as const;

export const breakpoint = {
  mobile: 640,
  tablet: 1024,
  desktop: 1280,
  wide: 1440,
  ultrawide: 1600,
} as const;

/** Mockup frame sizes (AppSurface). Phone matches the legacy 390×844 convention. */
export const frame = {
  phone: { width: 390, minHeight: 844 },
  tablet: { width: 820, minHeight: 1100 },
  desktop: { width: 1280 },
} as const;

export const wordmark = {
  fontFamily: fontFamily.display,
  fontWeight: 800,
  fontSizePx: 24,
  color: "var(--primary)",
} as const;

export const gastifyTokens = {
  palette,
  colors,
  cssVarFor,
  twKeyFor,
  fontFamily,
  fontWeight,
  fontSize,
  lineHeight,
  radius,
  spacing,
  shadow,
  motion,
  breakpoint,
  frame,
  wordmark,
} as const;

export default gastifyTokens;
