/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as StatementScanRouteImport } from './routes/statement-scan'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RecentScansRouteImport } from './routes/recent-scans'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as TransactionsTransactionIdRouteImport } from './routes/transactions/$transactionId'
import { Route as SettingsSubscriptionRouteImport } from './routes/settings/subscription'
import { Route as SettingsScanningRouteImport } from './routes/settings/scanning'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsPreferencesRouteImport } from './routes/settings/preferences'
import { Route as SettingsLimitsRouteImport } from './routes/settings/limits'
import { Route as SettingsGroupsRouteImport } from './routes/settings/groups'
import { Route as SettingsDataRouteImport } from './routes/settings/data'
import { Route as SettingsAppRouteImport } from './routes/settings/app'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as BatchReviewRouteImport } from './routes/batch/review'
import { Route as BatchCaptureRouteImport } from './routes/batch/capture'

const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const StatementScanRoute = StatementScanRouteImport.update({
  id: '/statement-scan',
  path: '/statement-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentScansRoute = RecentScansRouteImport.update({
  id: '/recent-scans',
  path: '/recent-scans',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsTransactionIdRoute =
  TransactionsTransactionIdRouteImport.update({
    id: '/transactions/$transactionId',
    path: '/transactions/$transactionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsSubscriptionRoute = SettingsSubscriptionRouteImport.update({
  id: '/settings/subscription',
  path: '/settings/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsScanningRoute = SettingsScanningRouteImport.update({
  id: '/settings/scanning',
  path: '/settings/scanning',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/settings/preferences',
  path: '/settings/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLimitsRoute = SettingsLimitsRouteImport.update({
  id: '/settings/limits',
  path: '/settings/limits',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGroupsRoute = SettingsGroupsRouteImport.update({
  id: '/settings/groups',
  path: '/settings/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/settings/data',
  path: '/settings/data',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAppRoute = SettingsAppRouteImport.update({
  id: '/settings/app',
  path: '/settings/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchReviewRoute = BatchReviewRouteImport.update({
  id: '/batch/review',
  path: '/batch/review',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchCaptureRoute = BatchCaptureRouteImport.update({
  id: '/batch/capture',
  path: '/batch/capture',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/history': typeof HistoryRoute
  '/insights': typeof InsightsRoute
  '/items': typeof ItemsRoute
  '/recent-scans': typeof RecentScansRoute
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/statement-scan': typeof StatementScanRoute
  '/trends': typeof TrendsRoute
  '/batch/capture': typeof BatchCaptureRoute
  '/batch/review': typeof BatchReviewRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/app': typeof SettingsAppRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/groups': typeof SettingsGroupsRoute
  '/settings/limits': typeof SettingsLimitsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/scanning': typeof SettingsScanningRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/history': typeof HistoryRoute
  '/insights': typeof InsightsRoute
  '/items': typeof ItemsRoute
  '/recent-scans': typeof RecentScansRoute
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/statement-scan': typeof StatementScanRoute
  '/trends': typeof TrendsRoute
  '/batch/capture': typeof BatchCaptureRoute
  '/batch/review': typeof BatchReviewRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/app': typeof SettingsAppRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/groups': typeof SettingsGroupsRoute
  '/settings/limits': typeof SettingsLimitsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/scanning': typeof SettingsScanningRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/settings': typeof SettingsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/history': typeof HistoryRoute
  '/insights': typeof InsightsRoute
  '/items': typeof ItemsRoute
  '/recent-scans': typeof RecentScansRoute
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/statement-scan': typeof StatementScanRoute
  '/trends': typeof TrendsRoute
  '/batch/capture': typeof BatchCaptureRoute
  '/batch/review': typeof BatchReviewRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/app': typeof SettingsAppRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/groups': typeof SettingsGroupsRoute
  '/settings/limits': typeof SettingsLimitsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/scanning': typeof SettingsScanningRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/history'
    | '/insights'
    | '/items'
    | '/recent-scans'
    | '/reports'
    | '/scan'
    | '/statement-scan'
    | '/trends'
    | '/batch/capture'
    | '/batch/review'
    | '/settings/account'
    | '/settings/app'
    | '/settings/data'
    | '/settings/groups'
    | '/settings/limits'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/scanning'
    | '/settings/subscription'
    | '/transactions/$transactionId'
    | '/settings/'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/history'
    | '/insights'
    | '/items'
    | '/recent-scans'
    | '/reports'
    | '/scan'
    | '/statement-scan'
    | '/trends'
    | '/batch/capture'
    | '/batch/review'
    | '/settings/account'
    | '/settings/app'
    | '/settings/data'
    | '/settings/groups'
    | '/settings/limits'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/scanning'
    | '/settings/subscription'
    | '/transactions/$transactionId'
    | '/settings'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/history'
    | '/insights'
    | '/items'
    | '/recent-scans'
    | '/reports'
    | '/scan'
    | '/statement-scan'
    | '/trends'
    | '/batch/capture'
    | '/batch/review'
    | '/settings/account'
    | '/settings/app'
    | '/settings/data'
    | '/settings/groups'
    | '/settings/limits'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/scanning'
    | '/settings/subscription'
    | '/transactions/$transactionId'
    | '/settings/'
    | '/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  HistoryRoute: typeof HistoryRoute
  InsightsRoute: typeof InsightsRoute
  ItemsRoute: typeof ItemsRoute
  RecentScansRoute: typeof RecentScansRoute
  ReportsRoute: typeof ReportsRoute
  ScanRoute: typeof ScanRoute
  StatementScanRoute: typeof StatementScanRoute
  TrendsRoute: typeof TrendsRoute
  BatchCaptureRoute: typeof BatchCaptureRoute
  BatchReviewRoute: typeof BatchReviewRoute
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsAppRoute: typeof SettingsAppRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsGroupsRoute: typeof SettingsGroupsRoute
  SettingsLimitsRoute: typeof SettingsLimitsRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsScanningRoute: typeof SettingsScanningRoute
  SettingsSubscriptionRoute: typeof SettingsSubscriptionRoute
  TransactionsTransactionIdRoute: typeof TransactionsTransactionIdRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statement-scan': {
      id: '/statement-scan'
      path: '/statement-scan'
      fullPath: '/statement-scan'
      preLoaderRoute: typeof StatementScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent-scans': {
      id: '/recent-scans'
      path: '/recent-scans'
      fullPath: '/recent-scans'
      preLoaderRoute: typeof RecentScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$transactionId': {
      id: '/transactions/$transactionId'
      path: '/transactions/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof TransactionsTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/subscription': {
      id: '/settings/subscription'
      path: '/settings/subscription'
      fullPath: '/settings/subscription'
      preLoaderRoute: typeof SettingsSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/scanning': {
      id: '/settings/scanning'
      path: '/settings/scanning'
      fullPath: '/settings/scanning'
      preLoaderRoute: typeof SettingsScanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/limits': {
      id: '/settings/limits'
      path: '/settings/limits'
      fullPath: '/settings/limits'
      preLoaderRoute: typeof SettingsLimitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/groups': {
      id: '/settings/groups'
      path: '/settings/groups'
      fullPath: '/settings/groups'
      preLoaderRoute: typeof SettingsGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/settings/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/app': {
      id: '/settings/app'
      path: '/settings/app'
      fullPath: '/settings/app'
      preLoaderRoute: typeof SettingsAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch/review': {
      id: '/batch/review'
      path: '/batch/review'
      fullPath: '/batch/review'
      preLoaderRoute: typeof BatchReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch/capture': {
      id: '/batch/capture'
      path: '/batch/capture'
      fullPath: '/batch/capture'
      preLoaderRoute: typeof BatchCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  HistoryRoute: HistoryRoute,
  InsightsRoute: InsightsRoute,
  ItemsRoute: ItemsRoute,
  RecentScansRoute: RecentScansRoute,
  ReportsRoute: ReportsRoute,
  ScanRoute: ScanRoute,
  StatementScanRoute: StatementScanRoute,
  TrendsRoute: TrendsRoute,
  BatchCaptureRoute: BatchCaptureRoute,
  BatchReviewRoute: BatchReviewRoute,
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsAppRoute: SettingsAppRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsGroupsRoute: SettingsGroupsRoute,
  SettingsLimitsRoute: SettingsLimitsRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsScanningRoute: SettingsScanningRoute,
  SettingsSubscriptionRoute: SettingsSubscriptionRoute,
  TransactionsTransactionIdRoute: TransactionsTransactionIdRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
