/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TransactionsRouteImport } from "./routes/transactions"
import { Route as StatementsRouteImport } from "./routes/statements"
import { Route as SignInRouteImport } from "./routes/sign-in"
import { Route as ScanRouteImport } from "./routes/scan"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as TransactionsIndexRouteImport } from "./routes/transactions.index"
import { Route as TransactionsTransactionIdRouteImport } from "./routes/transactions.$transactionId"

const TransactionsRoute = TransactionsRouteImport.update({
  id: "/transactions",
  path: "/transactions",
  getParentRoute: () => rootRouteImport,
} as any)
const StatementsRoute = StatementsRouteImport.update({
  id: "/statements",
  path: "/statements",
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: "/scan",
  path: "/scan",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => TransactionsRoute,
} as any)
const TransactionsTransactionIdRoute =
  TransactionsTransactionIdRouteImport.update({
    id: "/$transactionId",
    path: "/$transactionId",
    getParentRoute: () => TransactionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/scan": typeof ScanRoute
  "/sign-in": typeof SignInRoute
  "/statements": typeof StatementsRoute
  "/transactions": typeof TransactionsRouteWithChildren
  "/transactions/$transactionId": typeof TransactionsTransactionIdRoute
  "/transactions/": typeof TransactionsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/scan": typeof ScanRoute
  "/sign-in": typeof SignInRoute
  "/statements": typeof StatementsRoute
  "/transactions/$transactionId": typeof TransactionsTransactionIdRoute
  "/transactions": typeof TransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/scan": typeof ScanRoute
  "/sign-in": typeof SignInRoute
  "/statements": typeof StatementsRoute
  "/transactions": typeof TransactionsRouteWithChildren
  "/transactions/$transactionId": typeof TransactionsTransactionIdRoute
  "/transactions/": typeof TransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/scan"
    | "/sign-in"
    | "/statements"
    | "/transactions"
    | "/transactions/$transactionId"
    | "/transactions/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/scan"
    | "/sign-in"
    | "/statements"
    | "/transactions/$transactionId"
    | "/transactions"
  id:
    | "__root__"
    | "/"
    | "/scan"
    | "/sign-in"
    | "/statements"
    | "/transactions"
    | "/transactions/$transactionId"
    | "/transactions/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScanRoute: typeof ScanRoute
  SignInRoute: typeof SignInRoute
  StatementsRoute: typeof StatementsRoute
  TransactionsRoute: typeof TransactionsRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/transactions": {
      id: "/transactions"
      path: "/transactions"
      fullPath: "/transactions"
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/statements": {
      id: "/statements"
      path: "/statements"
      fullPath: "/statements"
      preLoaderRoute: typeof StatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sign-in": {
      id: "/sign-in"
      path: "/sign-in"
      fullPath: "/sign-in"
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/scan": {
      id: "/scan"
      path: "/scan"
      fullPath: "/scan"
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/transactions/": {
      id: "/transactions/"
      path: "/"
      fullPath: "/transactions/"
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof TransactionsRoute
    }
    "/transactions/$transactionId": {
      id: "/transactions/$transactionId"
      path: "/$transactionId"
      fullPath: "/transactions/$transactionId"
      preLoaderRoute: typeof TransactionsTransactionIdRouteImport
      parentRoute: typeof TransactionsRoute
    }
  }
}

interface TransactionsRouteChildren {
  TransactionsTransactionIdRoute: typeof TransactionsTransactionIdRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

const TransactionsRouteChildren: TransactionsRouteChildren = {
  TransactionsTransactionIdRoute: TransactionsTransactionIdRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}

const TransactionsRouteWithChildren = TransactionsRoute._addFileChildren(
  TransactionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScanRoute: ScanRoute,
  SignInRoute: SignInRoute,
  StatementsRoute: StatementsRoute,
  TransactionsRoute: TransactionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
