/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TrendsRouteImport } from "./routes/trends"
import { Route as TransactionsRouteImport } from "./routes/transactions"
import { Route as StatementsRouteImport } from "./routes/statements"
import { Route as SignInRouteImport } from "./routes/sign-in"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as ScanBatchRouteImport } from "./routes/scan-batch"
import { Route as ScanRouteImport } from "./routes/scan"
import { Route as ReportsRouteImport } from "./routes/reports"
import { Route as NotificationsRouteImport } from "./routes/notifications"
import { Route as ItemsRouteImport } from "./routes/items"
import { Route as GroupsRouteImport } from "./routes/groups"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as TransactionsIndexRouteImport } from "./routes/transactions.index"
import { Route as SettingsIndexRouteImport } from "./routes/settings.index"
import { Route as TransactionsNewRouteImport } from "./routes/transactions.new"
import { Route as TransactionsTransactionIdRouteImport } from "./routes/transactions.$transactionId"
import { Route as SettingsSubscriptionRouteImport } from "./routes/settings.subscription"
import { Route as SettingsScanningRouteImport } from "./routes/settings.scanning"
import { Route as SettingsProfileRouteImport } from "./routes/settings.profile"
import { Route as SettingsPreferencesRouteImport } from "./routes/settings.preferences"
import { Route as SettingsMemoryRouteImport } from "./routes/settings.memory"
import { Route as SettingsLimitsRouteImport } from "./routes/settings.limits"
import { Route as SettingsHelpRouteImport } from "./routes/settings.help"
import { Route as SettingsDataRouteImport } from "./routes/settings.data"
import { Route as SettingsCardsRouteImport } from "./routes/settings.cards"
import { Route as InviteTokenRouteImport } from "./routes/invite.$token"

const TrendsRoute = TrendsRouteImport.update({
  id: "/trends",
  path: "/trends",
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: "/transactions",
  path: "/transactions",
  getParentRoute: () => rootRouteImport,
} as any)
const StatementsRoute = StatementsRouteImport.update({
  id: "/statements",
  path: "/statements",
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const ScanBatchRoute = ScanBatchRouteImport.update({
  id: "/scan-batch",
  path: "/scan-batch",
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: "/scan",
  path: "/scan",
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: "/notifications",
  path: "/notifications",
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: "/items",
  path: "/items",
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: "/groups",
  path: "/groups",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => TransactionsRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SettingsRoute,
} as any)
const TransactionsNewRoute = TransactionsNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => TransactionsRoute,
} as any)
const TransactionsTransactionIdRoute =
  TransactionsTransactionIdRouteImport.update({
    id: "/$transactionId",
    path: "/$transactionId",
    getParentRoute: () => TransactionsRoute,
  } as any)
const SettingsSubscriptionRoute = SettingsSubscriptionRouteImport.update({
  id: "/subscription",
  path: "/subscription",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsScanningRoute = SettingsScanningRouteImport.update({
  id: "/scanning",
  path: "/scanning",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: "/preferences",
  path: "/preferences",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMemoryRoute = SettingsMemoryRouteImport.update({
  id: "/memory",
  path: "/memory",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLimitsRoute = SettingsLimitsRouteImport.update({
  id: "/limits",
  path: "/limits",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsHelpRoute = SettingsHelpRouteImport.update({
  id: "/help",
  path: "/help",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: "/data",
  path: "/data",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCardsRoute = SettingsCardsRouteImport.update({
  id: "/cards",
  path: "/cards",
  getParentRoute: () => SettingsRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: "/invite/$token",
  path: "/invite/$token",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/groups": typeof GroupsRoute
  "/items": typeof ItemsRoute
  "/notifications": typeof NotificationsRoute
  "/reports": typeof ReportsRoute
  "/scan": typeof ScanRoute
  "/scan-batch": typeof ScanBatchRoute
  "/settings": typeof SettingsRouteWithChildren
  "/sign-in": typeof SignInRoute
  "/statements": typeof StatementsRoute
  "/transactions": typeof TransactionsRouteWithChildren
  "/trends": typeof TrendsRoute
  "/invite/$token": typeof InviteTokenRoute
  "/settings/cards": typeof SettingsCardsRoute
  "/settings/data": typeof SettingsDataRoute
  "/settings/help": typeof SettingsHelpRoute
  "/settings/limits": typeof SettingsLimitsRoute
  "/settings/memory": typeof SettingsMemoryRoute
  "/settings/preferences": typeof SettingsPreferencesRoute
  "/settings/profile": typeof SettingsProfileRoute
  "/settings/scanning": typeof SettingsScanningRoute
  "/settings/subscription": typeof SettingsSubscriptionRoute
  "/transactions/$transactionId": typeof TransactionsTransactionIdRoute
  "/transactions/new": typeof TransactionsNewRoute
  "/settings/": typeof SettingsIndexRoute
  "/transactions/": typeof TransactionsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/groups": typeof GroupsRoute
  "/items": typeof ItemsRoute
  "/notifications": typeof NotificationsRoute
  "/reports": typeof ReportsRoute
  "/scan": typeof ScanRoute
  "/scan-batch": typeof ScanBatchRoute
  "/sign-in": typeof SignInRoute
  "/statements": typeof StatementsRoute
  "/trends": typeof TrendsRoute
  "/invite/$token": typeof InviteTokenRoute
  "/settings/cards": typeof SettingsCardsRoute
  "/settings/data": typeof SettingsDataRoute
  "/settings/help": typeof SettingsHelpRoute
  "/settings/limits": typeof SettingsLimitsRoute
  "/settings/memory": typeof SettingsMemoryRoute
  "/settings/preferences": typeof SettingsPreferencesRoute
  "/settings/profile": typeof SettingsProfileRoute
  "/settings/scanning": typeof SettingsScanningRoute
  "/settings/subscription": typeof SettingsSubscriptionRoute
  "/transactions/$transactionId": typeof TransactionsTransactionIdRoute
  "/transactions/new": typeof TransactionsNewRoute
  "/settings": typeof SettingsIndexRoute
  "/transactions": typeof TransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/groups": typeof GroupsRoute
  "/items": typeof ItemsRoute
  "/notifications": typeof NotificationsRoute
  "/reports": typeof ReportsRoute
  "/scan": typeof ScanRoute
  "/scan-batch": typeof ScanBatchRoute
  "/settings": typeof SettingsRouteWithChildren
  "/sign-in": typeof SignInRoute
  "/statements": typeof StatementsRoute
  "/transactions": typeof TransactionsRouteWithChildren
  "/trends": typeof TrendsRoute
  "/invite/$token": typeof InviteTokenRoute
  "/settings/cards": typeof SettingsCardsRoute
  "/settings/data": typeof SettingsDataRoute
  "/settings/help": typeof SettingsHelpRoute
  "/settings/limits": typeof SettingsLimitsRoute
  "/settings/memory": typeof SettingsMemoryRoute
  "/settings/preferences": typeof SettingsPreferencesRoute
  "/settings/profile": typeof SettingsProfileRoute
  "/settings/scanning": typeof SettingsScanningRoute
  "/settings/subscription": typeof SettingsSubscriptionRoute
  "/transactions/$transactionId": typeof TransactionsTransactionIdRoute
  "/transactions/new": typeof TransactionsNewRoute
  "/settings/": typeof SettingsIndexRoute
  "/transactions/": typeof TransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/groups"
    | "/items"
    | "/notifications"
    | "/reports"
    | "/scan"
    | "/scan-batch"
    | "/settings"
    | "/sign-in"
    | "/statements"
    | "/transactions"
    | "/trends"
    | "/invite/$token"
    | "/settings/cards"
    | "/settings/data"
    | "/settings/help"
    | "/settings/limits"
    | "/settings/memory"
    | "/settings/preferences"
    | "/settings/profile"
    | "/settings/scanning"
    | "/settings/subscription"
    | "/transactions/$transactionId"
    | "/transactions/new"
    | "/settings/"
    | "/transactions/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/groups"
    | "/items"
    | "/notifications"
    | "/reports"
    | "/scan"
    | "/scan-batch"
    | "/sign-in"
    | "/statements"
    | "/trends"
    | "/invite/$token"
    | "/settings/cards"
    | "/settings/data"
    | "/settings/help"
    | "/settings/limits"
    | "/settings/memory"
    | "/settings/preferences"
    | "/settings/profile"
    | "/settings/scanning"
    | "/settings/subscription"
    | "/transactions/$transactionId"
    | "/transactions/new"
    | "/settings"
    | "/transactions"
  id:
    | "__root__"
    | "/"
    | "/groups"
    | "/items"
    | "/notifications"
    | "/reports"
    | "/scan"
    | "/scan-batch"
    | "/settings"
    | "/sign-in"
    | "/statements"
    | "/transactions"
    | "/trends"
    | "/invite/$token"
    | "/settings/cards"
    | "/settings/data"
    | "/settings/help"
    | "/settings/limits"
    | "/settings/memory"
    | "/settings/preferences"
    | "/settings/profile"
    | "/settings/scanning"
    | "/settings/subscription"
    | "/transactions/$transactionId"
    | "/transactions/new"
    | "/settings/"
    | "/transactions/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupsRoute: typeof GroupsRoute
  ItemsRoute: typeof ItemsRoute
  NotificationsRoute: typeof NotificationsRoute
  ReportsRoute: typeof ReportsRoute
  ScanRoute: typeof ScanRoute
  ScanBatchRoute: typeof ScanBatchRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SignInRoute: typeof SignInRoute
  StatementsRoute: typeof StatementsRoute
  TransactionsRoute: typeof TransactionsRouteWithChildren
  TrendsRoute: typeof TrendsRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/trends": {
      id: "/trends"
      path: "/trends"
      fullPath: "/trends"
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/transactions": {
      id: "/transactions"
      path: "/transactions"
      fullPath: "/transactions"
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/statements": {
      id: "/statements"
      path: "/statements"
      fullPath: "/statements"
      preLoaderRoute: typeof StatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sign-in": {
      id: "/sign-in"
      path: "/sign-in"
      fullPath: "/sign-in"
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/scan-batch": {
      id: "/scan-batch"
      path: "/scan-batch"
      fullPath: "/scan-batch"
      preLoaderRoute: typeof ScanBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/scan": {
      id: "/scan"
      path: "/scan"
      fullPath: "/scan"
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reports": {
      id: "/reports"
      path: "/reports"
      fullPath: "/reports"
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/notifications": {
      id: "/notifications"
      path: "/notifications"
      fullPath: "/notifications"
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/items": {
      id: "/items"
      path: "/items"
      fullPath: "/items"
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/groups": {
      id: "/groups"
      path: "/groups"
      fullPath: "/groups"
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/transactions/": {
      id: "/transactions/"
      path: "/"
      fullPath: "/transactions/"
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof TransactionsRoute
    }
    "/settings/": {
      id: "/settings/"
      path: "/"
      fullPath: "/settings/"
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/transactions/new": {
      id: "/transactions/new"
      path: "/new"
      fullPath: "/transactions/new"
      preLoaderRoute: typeof TransactionsNewRouteImport
      parentRoute: typeof TransactionsRoute
    }
    "/transactions/$transactionId": {
      id: "/transactions/$transactionId"
      path: "/$transactionId"
      fullPath: "/transactions/$transactionId"
      preLoaderRoute: typeof TransactionsTransactionIdRouteImport
      parentRoute: typeof TransactionsRoute
    }
    "/settings/subscription": {
      id: "/settings/subscription"
      path: "/subscription"
      fullPath: "/settings/subscription"
      preLoaderRoute: typeof SettingsSubscriptionRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/scanning": {
      id: "/settings/scanning"
      path: "/scanning"
      fullPath: "/settings/scanning"
      preLoaderRoute: typeof SettingsScanningRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/profile": {
      id: "/settings/profile"
      path: "/profile"
      fullPath: "/settings/profile"
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/preferences": {
      id: "/settings/preferences"
      path: "/preferences"
      fullPath: "/settings/preferences"
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/memory": {
      id: "/settings/memory"
      path: "/memory"
      fullPath: "/settings/memory"
      preLoaderRoute: typeof SettingsMemoryRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/limits": {
      id: "/settings/limits"
      path: "/limits"
      fullPath: "/settings/limits"
      preLoaderRoute: typeof SettingsLimitsRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/help": {
      id: "/settings/help"
      path: "/help"
      fullPath: "/settings/help"
      preLoaderRoute: typeof SettingsHelpRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/data": {
      id: "/settings/data"
      path: "/data"
      fullPath: "/settings/data"
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/cards": {
      id: "/settings/cards"
      path: "/cards"
      fullPath: "/settings/cards"
      preLoaderRoute: typeof SettingsCardsRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/invite/$token": {
      id: "/invite/$token"
      path: "/invite/$token"
      fullPath: "/invite/$token"
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsCardsRoute: typeof SettingsCardsRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsHelpRoute: typeof SettingsHelpRoute
  SettingsLimitsRoute: typeof SettingsLimitsRoute
  SettingsMemoryRoute: typeof SettingsMemoryRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsScanningRoute: typeof SettingsScanningRoute
  SettingsSubscriptionRoute: typeof SettingsSubscriptionRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsCardsRoute: SettingsCardsRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsHelpRoute: SettingsHelpRoute,
  SettingsLimitsRoute: SettingsLimitsRoute,
  SettingsMemoryRoute: SettingsMemoryRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsScanningRoute: SettingsScanningRoute,
  SettingsSubscriptionRoute: SettingsSubscriptionRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface TransactionsRouteChildren {
  TransactionsTransactionIdRoute: typeof TransactionsTransactionIdRoute
  TransactionsNewRoute: typeof TransactionsNewRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

const TransactionsRouteChildren: TransactionsRouteChildren = {
  TransactionsTransactionIdRoute: TransactionsTransactionIdRoute,
  TransactionsNewRoute: TransactionsNewRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}

const TransactionsRouteWithChildren = TransactionsRoute._addFileChildren(
  TransactionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupsRoute: GroupsRoute,
  ItemsRoute: ItemsRoute,
  NotificationsRoute: NotificationsRoute,
  ReportsRoute: ReportsRoute,
  ScanRoute: ScanRoute,
  ScanBatchRoute: ScanBatchRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SignInRoute: SignInRoute,
  StatementsRoute: StatementsRoute,
  TransactionsRoute: TransactionsRouteWithChildren,
  TrendsRoute: TrendsRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
