/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TransactionsRouteImport } from "./routes/transactions"
import { Route as SignInRouteImport } from "./routes/sign-in"
import { Route as ScanRouteImport } from "./routes/scan"
import { Route as IndexRouteImport } from "./routes/index"

const TransactionsRoute = TransactionsRouteImport.update({
  id: "/transactions",
  path: "/transactions",
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: "/scan",
  path: "/scan",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/scan": typeof ScanRoute
  "/sign-in": typeof SignInRoute
  "/transactions": typeof TransactionsRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/scan": typeof ScanRoute
  "/sign-in": typeof SignInRoute
  "/transactions": typeof TransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/scan": typeof ScanRoute
  "/sign-in": typeof SignInRoute
  "/transactions": typeof TransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/scan" | "/sign-in" | "/transactions"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/scan" | "/sign-in" | "/transactions"
  id: "__root__" | "/" | "/scan" | "/sign-in" | "/transactions"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScanRoute: typeof ScanRoute
  SignInRoute: typeof SignInRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/transactions": {
      id: "/transactions"
      path: "/transactions"
      fullPath: "/transactions"
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sign-in": {
      id: "/sign-in"
      path: "/sign-in"
      fullPath: "/sign-in"
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/scan": {
      id: "/scan"
      path: "/scan"
      fullPath: "/scan"
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScanRoute: ScanRoute,
  SignInRoute: SignInRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
